name: ccc

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#  schedule:
#    - cron:  '0 0 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https ca-certificates wget whois
      - run: bash ./gen-china-tlds.sh
      - run: echo "# CN_Root_Zone">README.md
      - run: echo '```'>>README.md
      - run: cat china-tlds.txt >>README.md
      - run: echo '```'>>README.md
      - run: rm *.txt*
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Robot update"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
